apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.db.name }}
  owner: {{ .Values.db.owner }}
spec:
  instances: {{ .Values.db.instances }}
  resources:
    requests:
      cpu: {{ .Values.db.resources.requests.cpu }}
      memory: {{ .Values.db.resources.requests.memory }}
    limits:
      cpu: {{ .Values.db.resources.limits.cpu }}
      memory: {{.Values.db.resources.limits.memory }}
  storage:
    size: {{ .Values.db.storage.size }}
    storageClass: {{ .Values.db.storage.storageClass }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.db.backup.path }}
      endpointURL: {{ .Values.db.backup.url }}
      s3Credentials:
        accessKeyId:
          name: minio-s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-s3-creds
          key: ACCESS_SECRET_KEY
