apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.db.name }}
spec:
  instances: {{ .Values.db.instances }}
 
  imageName: 'ghcr.io/cloudnative-pg/postgresql:14.7-3'
 
  primaryUpdateStrategy: unsupervised
 
  bootstrap:
    initdb:
      database: {{ .Values.db.name | quote }}
      owner: {{ .Values.db.owner | toString | quote }}
 
  resources: {{ .Values.db.resources | toYaml | nindent 4 }}
 
  storage: {{ .Values.db.storage | toYaml | nindent 4 }}

  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.db.backup.path }}
      endpointURL: {{ .Values.db.backup.url }}
      s3Credentials:
        accessKeyId:
          name: minio-s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-s3-creds
          key: ACCESS_SECRET_KEY
