apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      app: apache
  template:
    spec: 
      securityContext:
        runAsUser: 33
      containers:
      - name: apache
        image: {{ .Values.image }}
        volumeMounts:
          - name: php-script
            mountPath: /var/www/html/{{ .Values.tenant.buckets.0.name }}.php
            subPath: {{ .Values.tenant.buckets.0.name }}.php
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-minio-creds
                key: accesskey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-minio-creds
                key: secretkey
          - name: AWS_S3_ENDPOINT
            value: "http://{{ .Values.tenant.tenant.name }}-hl:9000"
    volumes:
      - name: php-script
        configMap:
          name: {{ .Release.Name }}-php-script
