apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec: 
      securityContext:
        runAsUser: 33
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: apache
          image: {{ .Values.image }}
          securityContext:
            runAsUser: 33
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: php-script
              mountPath: /var/www/html/485230.php
              subPath: 485230.php
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-s3-creds
                  key: ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-s3-creds
                  key: ACCESS_SECRET_KEY
      
      volumes:
        - name: php-script
          configMap:
            name: cm-php
