apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache
            port:
              number: 80
