apiVersion: v1
data:
  ACCESS_KEY_ID: {{ .Values.s3.access_key | b64enc | quote }}
  ACCESS_SECRET_KEY: {{ .Values.s3.secret_key | b64enc | quote }}
kind: Secret
metadata:
  name: minio-s3-creds
type: Opaque
