apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
data:
  CONSOLE_ACCESS_KEY: {{ .Values.s3.access_key | b64enc | quote }}
  CONSOLE_SECRET_KEY: {{ .Values.s3.secret_key | b64enc | quote }}

