apiVersion: v1
kind: Service
metadata:
  name: {{ include "pa234-hw02-485230.fullname" . }}
  labels:
    {{- include "pa234-hw02-485230.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pa234-hw02-485230.selectorLabels" . | nindent 4 }}
