apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ .Values.tenant.tenant.name }}
spec:
  name: {{ .Values.tenant.tenant.name }}
  users: {{- .Values.tenant.tenant.users | toYaml | nindent 4 }}
  buckets: {{- .Values.tenant.tenant.buckets | toYaml | nindent 4 }}
  certificate: {{- .Values.tenant.tenant.certificate | toYaml | nindent 4 }}
  pools: {{- .Values.tenant.tenant.pools | toYaml | nindent 4}}
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
